### ISSUE TITLE
`allOptions` input doesn't do anything

### ISSUE THREAD

**Issue by electrovir** [electrovir/pdf-text-reader#12]
this input: https://github.com/electrovir/pdf-text-reader/blob/c33bcfc4d698552bb064f233e3c5774292e106e6/src/read-pdf.ts#L59

**Comment by electrovir** [comment]
fix in v4 as well

**Comment by electrovir** [comment]
Fixed in v5: https://www.npmjs.com/package/pdf-text-reader/v/5.1.0
Fixed in v4: https://www.npmjs.com/package/pdf-text-reader/v/4.1.0

Also, `allOptions` was renamed to `options`.

**Comment by electrovir** [comment]
@AaronSterlingGENEICD does v4.1 work well for you? (regarding https://github.com/electrovir/pdf-text-reader/issues/11#issuecomment-2100611217)

**Comment by AaronSterlingGENEICD** [comment]
Yes thank you! The code below works fine.
```
const pdfText = await readPdfText({
      data: atob(base64string),
      options: {isEvalSupported: false}
    });
```
